const API_URL='https://hdxlhxqlkdipqkwisjyd.supabase.co/rest/v1/public_live_motorcycle_listings?select=*&order=ends_at.desc.nullslast&limit=200';
const API_KEY='sb_publishable_O5FXZ4ecH2vFAlkRrCU0Ew_K831f3B2';
const DAY=86400000;
const classLabels={ORDINARY_LIGHT:'普通輕型',ORDINARY_HEAVY:'普通重型',LARGE_HEAVY:'大型重型',ELECTRIC_MOTORCYCLE:'電動機車',HEAVY_UNSPECIFIED:'重型（級別未明）',UNKNOWN:'級別未確認'};
const eligibilityLabels={PUBLIC:'一般民眾可投標',NATURAL_PERSON_ALLOWED:'一般民眾可投標',BUSINESS_ONLY:'限事業單位',LICENSED_RECYCLER_ONLY:'限合格回收商',SPECIAL_QUALIFICATION:'需特別資格',BULK_PURCHASE_ONLY:'限整批投標',UNKNOWN:'投標資格未確認'};
const registrationLabels={NORMAL_TRANSFER:'可正常過戶',RE_REGISTRATION_REQUIRED:'需重新領牌',INSPECTION_REQUIRED:'需檢驗後領牌',REGISTRABILITY_UNKNOWN:'能否領牌未確認',DEREGISTERED:'牌照已繳銷',CANNOT_RELICENSE:'不得再領牌',SCRAP_ONLY:'僅供報廢／回收',EXPORT_ONLY:'僅供出口',UNKNOWN:'牌照狀態未確認'};
const statusLabels={DISCOVERED:'已發現',ANNOUNCED:'已公告',SCHEDULED:'進行中',SOLD:'已得標',UNSOLD:'未得標',WITHDRAWN:'已撤回',CANCELLED:'已取消',EXPIRED:'已截止',UNKNOWN:'結果待官方確認'};
const brandLabels={KYMCO:'光陽',SYM:'三陽',YAMAHA:'山葉'};
const state={view:'active',keyword:'',vehicleClass:'',cc:'',hasPhotos:false,rows:[]};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function safeOfficialUrl(value){try{const u=new URL(value);const allowed=['shwoo.gov.taipei','aomp109.judicial.gov.tw','auction.moj.gov.tw'].includes(u.hostname);return u.protocol==='https:'&&allowed?u.href:null}catch{return null}}
function formatPrice(v){return v==null?'官方未提供':`新臺幣 ${Number(v).toLocaleString('zh-TW')} 元`}
function formatDate(v){if(!v)return'日期未確認';return new Intl.DateTimeFormat('zh-TW',{timeZone:'Asia/Taipei',year:'numeric',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(v))}
function isEnded(item){return ['SOLD','UNSOLD','WITHDRAWN','CANCELLED','EXPIRED'].includes(item.auction_status)||(item.ends_at&&new Date(item.ends_at)<new Date())}
function ccMatch(v,b){if(b==='unknown')return v==null;if(v==null)return false;v=Number(v);return b==='le-50'?v<=50:b==='51-125'?v>=51&&v<=125:b==='126-250'?v>=126&&v<=250:b==='251-550'?v>=251&&v<=550:v>550}
function filtered(){const now=Date.now(),q=state.keyword.toLocaleLowerCase('zh-TW').replace(/\s/g,'');return state.rows.filter(item=>{const ended=isEnded(item),scheduled=!ended&&(item.auction_status==='SCHEDULED'||Boolean(item.ends_at&&new Date(item.ends_at).getTime()>=now));if(state.view==='active'&&!scheduled)return false;if(state.view==='ended'&&!ended)return false;if(state.view==='within30'&&(ended||!item.ends_at||new Date(item.ends_at).getTime()>now+30*DAY))return false;if(q&&!Object.values(item).filter(v=>typeof v==='string').join(' ').toLocaleLowerCase('zh-TW').replace(/\s/g,'').includes(q))return false;if(state.vehicleClass&&item.vehicle_category!==state.vehicleClass)return false;if(state.cc&&!ccMatch(item.displacement_cc,state.cc))return false;if(state.hasPhotos&&!(Array.isArray(item.photo_urls)&&item.photo_urls.length))return false;return true}).sort((a,b)=>{const ae=isEnded(a),be=isEnded(b);if(ae!==be)return ae?1:-1;const at=a.ends_at?new Date(a.ends_at).getTime():Number.MAX_SAFE_INTEGER,bt=b.ends_at?new Date(b.ends_at).getTime():Number.MAX_SAFE_INTEGER;return ae?bt-at:at-bt})}
function photoMarkup(item){const urls=(Array.isArray(item.photo_urls)?item.photo_urls:[]).map(safeOfficialUrl).filter(Boolean);if(!urls.length)return`<div class="no-photo"><span>官方未提供可辨識照片</span></div>`;return`<div class="photo-carousel" data-index="0">${urls.map((url,i)=>`<img src="${esc(url)}" alt="${esc(item.official_title)} 官方照片 ${i+1}" loading="lazy" ${i?'hidden':''}>`).join('')}${urls.length>1?`<button class="photo-prev" type="button" aria-label="上一張照片">‹</button><button class="photo-next" type="button" aria-label="下一張照片">›</button><span class="photo-count">1 / ${urls.length}</span>`:''}<span class="official-photo">官方來源照片</span></div>`}
function fact(label,value){return`<div><dt>${esc(label)}</dt><dd>${esc(value??'官方未提供')}</dd></div>`}
function card(item){const official=safeOfficialUrl(item.official_url);const price=item.sold_price??item.current_price??item.reserve_price;const brand=brandLabels[item.brand_name]||item.brand_name;const heading=brand||item.model_name?[brand,item.model_name].filter(Boolean).join(' '):item.official_title;const officialLabel=item.source_adapter==='judicial'?'查看法院完整公告（官方 PDF） ↗':'查看官方完整公告 ↗';const article=document.createElement('article');article.className='card';article.innerHTML=`${photoMarkup(item)}<div class="card-body"><div class="source"><i></i>${esc(item.source_name)}<span class="status ${isEnded(item)?'ended':'active-status'}">${esc(statusLabels[item.auction_status]||'狀態未確認')}</span></div><h3>${esc(heading)}</h3><p class="official-title">${esc(item.official_title)}</p><div class="gates"><div class="gate"><span>誰能投標</span><strong>${esc(eligibilityLabels[item.eligibility]||'未確認')}</strong></div><div class="gate"><span>能否領牌</span><strong>${esc(registrationLabels[item.registration_status]||'未確認')}</strong></div></div><dl class="facts">${fact('車牌',item.plate_number||'官方未提供／已逾公開期')}${fact('官方案號',item.official_case_number||'官方未提供')}${fact('法定級別',classLabels[item.vehicle_category]||'級別未確認')}${fact('排氣量',item.displacement_cc==null?'官方未提供':`${item.displacement_cc} c.c.`)}${fact('價格',formatPrice(price))}${fact('拍賣截止',formatDate(item.ends_at))}${fact('拍賣機關',item.organization_name)}${fact('地點',item.location||'官方未提供')}${fact('拍賣次數',item.auction_round?`第 ${item.auction_round} 次`:'官方未提供')}</dl>${item.condition_summary?`<p class="condition">${esc(item.condition_summary)}</p>`:''}<div class="card-actions">${official?`<a class="official-link" href="${esc(official)}" target="_blank" rel="noopener noreferrer">${officialLabel}</a>`:''}<span>資料完整度 ${Number(item.completeness||0)}%</span></div></div>`;wireCarousel(article);return article}
function wireCarousel(article){const c=article.querySelector('.photo-carousel');if(!c)return;const imgs=[...c.querySelectorAll('img')],count=c.querySelector('.photo-count');function show(n){n=(n+imgs.length)%imgs.length;c.dataset.index=n;imgs.forEach((img,i)=>img.hidden=i!==n);if(count)count.textContent=`${n+1} / ${imgs.length}`}c.querySelector('.photo-prev')?.addEventListener('click',()=>show(Number(c.dataset.index)-1));c.querySelector('.photo-next')?.addEventListener('click',()=>show(Number(c.dataset.index)+1));imgs.forEach(img=>img.addEventListener('error',()=>{img.hidden=true;c.classList.add('image-error')}))}
function render(){const items=filtered();$('#results').replaceChildren(...items.map(card));$('#empty').hidden=items.length!==0||!state.rows.length;const labels={active:'進行中',within30:'未來 30 天',ended:'已結束',all:'全部正式案件'};const parts=[labels[state.view],state.keyword?`搜尋「${state.keyword}」`:null,state.vehicleClass?classLabels[state.vehicleClass]:null,state.cc?$('#cc').selectedOptions[0].text:null,state.hasPhotos?'有照片':null,`共 ${items.length} 筆`].filter(Boolean);$('#summary').textContent=parts.join('・');$('#chips').replaceChildren(...parts.slice(0,-1).map(t=>{const s=document.createElement('span');s.className='chip';s.textContent=t;return s}));$$('.tabs button').forEach(b=>{const on=b.dataset.view===state.view;b.classList.toggle('active',on);b.setAttribute('aria-selected',String(on))});const p=new URLSearchParams();if(state.view!=='all')p.set('view',state.view);if(state.keyword)p.set('q',state.keyword);if(state.vehicleClass)p.set('class',state.vehicleClass);if(state.cc)p.set('cc',state.cc);if(state.hasPhotos)p.set('photos','1');history.replaceState(null,'',`${location.pathname}${p.size?`?${p}`:''}`)}
function readUrl(){const p=new URLSearchParams(location.search),view=p.get('view');state.view=['active','within30','ended','all'].includes(view)?view:'active';state.keyword=(p.get('q')||'').slice(0,80);state.vehicleClass=Object.hasOwn(classLabels,p.get('class'))?p.get('class'):'';state.cc=['le-50','51-125','126-250','251-550','gt-550','unknown'].includes(p.get('cc'))?p.get('cc'):'';state.hasPhotos=p.get('photos')==='1';$('#keyword').value=state.keyword;$('#vehicleClass').value=state.vehicleClass;$('#cc').value=state.cc;$('#hasPhotos').checked=state.hasPhotos}
async function load(){ $('#loading').hidden=false;$('#error').hidden=true;$('#empty').hidden=true;try{const response=await fetch(API_URL,{headers:{apikey:API_KEY,Authorization:`Bearer ${API_KEY}`},cache:'no-store'});if(!response.ok)throw new Error(`HTTP ${response.status}`);const rows=await response.json();if(!Array.isArray(rows))throw new Error('資料格式錯誤');state.rows=rows;const latest=rows.map(r=>r.last_synced_at).filter(Boolean).sort().at(-1);$('#syncStatus').textContent=latest?`最近同步 ${formatDate(latest)}`:'目前尚無案件';const sourceLabels={judicial:'司法院官方公告',shwoo:'臺北惜物網',moj_auction:'法務部集中拍賣',moj_enforcement:'行政執行署'};const counts=rows.reduce((all,row)=>{const key=sourceLabels[row.source_adapter]||row.source_name||'其他官方來源';all[key]=(all[key]||0)+1;return all},{});$('#sourceCounts').textContent=Object.entries(counts).map(([name,count])=>`${name} ${count} 筆`).join('・');render()}catch(error){console.error(error);$('#error').hidden=false;$('#syncStatus').textContent='資料暫時離線';$('#sourceCounts').textContent='正式資料暫時無法統計'}finally{$('#loading').hidden=true}}
$$('.tabs button').forEach(b=>b.addEventListener('click',()=>{state.view=b.dataset.view;render()}));$('#filters').addEventListener('submit',e=>{e.preventDefault();state.keyword=$('#keyword').value.trim();state.vehicleClass=$('#vehicleClass').value;state.cc=$('#cc').value;state.hasPhotos=$('#hasPhotos').checked;render()});$('#clearFilters').addEventListener('click',()=>{state.keyword='';state.vehicleClass='';state.cc='';state.hasPhotos=false;$('#filters').reset();render()});$('#retry').addEventListener('click',load);readUrl();load();
