const DAY = 86400000;
const classLabels = {ORDINARY_LIGHT:'普通輕型',ORDINARY_HEAVY:'普通重型',LARGE_HEAVY:'大型重型',ELECTRIC_MOTORCYCLE:'電動機車',HEAVY_UNSPECIFIED:'重型（級別未明）',UNKNOWN:'級別未確認'};
const ccLabels = {'le-50':'50 以下 c.c.','51-125':'51–125 c.c.','126-250':'126–250 c.c.','251-550':'251–550 c.c.','gt-550':'551 以上 c.c.',unknown:'排氣量未提供'};
const baseCases = [
  {id:'synthetic-a',title:'都會通勤機車 A',source:'政府標售來源示意',county:'臺北市',vehicleClass:'ORDINARY_HEAVY',cc:125,days:5,price:18000,eligibility:'一般民眾可投標',registration:'需重新確認領牌條件',condition:'有鑰匙；發動狀態未確認',tone:'green'},
  {id:'synthetic-b',title:'大型重型機車 B',source:'司法拍賣來源示意',county:'臺中市',vehicleClass:'LARGE_HEAVY',cc:550,days:12,price:86000,eligibility:'投標資格未確認',registration:'牌照狀態未確認',condition:'可否測試未確認',tone:'copper'},
  {id:'synthetic-c',title:'電動機車 C',source:'公有財產標售示意',county:'高雄市',vehicleClass:'ELECTRIC_MOTORCYCLE',cc:null,days:26,price:12500,eligibility:'一般民眾可投標',registration:'可正常過戶',condition:'電池健康度未確認',tone:'blue'},
  {id:'synthetic-e',title:'重型機車 E',source:'機關公告來源示意',county:'新北市',vehicleClass:'HEAVY_UNSPECIFIED',cc:250,days:42,price:null,eligibility:'一般民眾可投標',registration:'領牌條件未確認',condition:'官方僅標示重型；級別不自行推定',tone:'green'},
  {id:'synthetic-d',title:'普通輕型機車 D',source:'歷史案件示意',county:'臺南市',vehicleClass:'ORDINARY_LIGHT',cc:50,days:-14,price:null,eligibility:'一般民眾可投標',registration:'結果待官方確認',condition:'已截止不代表已成交',tone:'copper'},
  {id:'synthetic-f',title:'普通重型機車 F',source:'歷史標售來源示意',county:'桃園市',vehicleClass:'ORDINARY_HEAVY',cc:150,days:-31,price:23000,eligibility:'投標資格已公開',registration:'車籍狀態未確認',condition:'拍賣結果未公開',tone:'blue'}
];
const state={view:'active',within:null,vehicleClass:'',cc:[]};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function matchesCc(value,band){if(band==='unknown')return value===null;if(value===null)return false;if(band==='le-50')return value<=50;if(band==='51-125')return value>=51&&value<=125;if(band==='126-250')return value>=126&&value<=250;if(band==='251-550')return value>=251&&value<=550;if(band==='gt-550')return value>550;return false}
function cases(){return baseCases.filter(item=>{if(state.view==='ended'&&item.days>=0)return false;if(state.view!=='ended'&&item.days<0)return false;if(state.within&&item.days>state.within)return false;if(state.vehicleClass&&item.vehicleClass!==state.vehicleClass)return false;if(state.cc.length&&!state.cc.some(b=>matchesCc(item.cc,b)))return false;return true})}
function dateText(days){const date=new Date(Date.now()+days*DAY);return new Intl.DateTimeFormat('zh-TW',{month:'numeric',day:'numeric',timeZone:'Asia/Taipei'}).format(date)}
function formatPrice(value){return value===null?'未公開':`NT$ ${value.toLocaleString('zh-TW')}`}
function card(item){const article=document.createElement('article');article.className='card';article.innerHTML=`<div class="card-visual ${item.tone}"><span>SYNTHETIC IMAGE · 非官方照片</span><strong>合成示意影像</strong></div><div class="card-body"><div class="source"><i></i>${item.source}<span>${item.county}</span></div><h3>${item.title}</h3><div class="gates"><div class="gate"><span>誰能投標</span><strong>${item.eligibility}</strong></div><div class="gate"><span>能否上路</span><strong>${item.registration}</strong></div></div><dl class="facts"><div><dt>法定級別</dt><dd>${classLabels[item.vehicleClass]}</dd></div><div><dt>排氣量</dt><dd>${item.cc===null?'官方未提供':`${item.cc} c.c.`}</dd></div><div><dt>示意價格</dt><dd>${formatPrice(item.price)}</dd></div><div><dt>拍賣時間</dt><dd>${dateText(item.days)}</dd></div></dl><p class="condition">${item.condition}</p><span class="card-note">合成案例・不可用於投標</span></div>`;return article}
function syncUrl(){const p=new URLSearchParams();p.set('view',state.view);if(state.within)p.set('within',String(state.within));if(state.vehicleClass)p.set('vehicleClass',state.vehicleClass);state.cc.forEach(v=>p.append('cc',v));history.replaceState(null,'',`${location.pathname}?${p}`)}
function render(){const items=cases();const results=$('#results');results.replaceChildren(...items.map(card));$('#empty').hidden=items.length!==0;const parts=[state.view==='ended'?'已結束':'進行中',state.within?`${state.within} 天內`:null,state.vehicleClass?classLabels[state.vehicleClass]:null,...state.cc.map(v=>ccLabels[v]),`共 ${items.length} 筆`].filter(Boolean);$('#summary').textContent=parts.join('・');$('#chips').replaceChildren(...parts.slice(0,-1).map(t=>{const s=document.createElement('span');s.className='chip';s.textContent=t;return s}));$$('.tabs button').forEach(b=>{const active=b.dataset.view==='ended'?state.view==='ended':b.dataset.view==='within30'?state.view==='active'&&state.within===30:state.view==='active'&&state.within!==30;b.classList.toggle('active',active);b.setAttribute('aria-selected',String(active))});$('#within').disabled=state.view==='ended';syncUrl()}
function readUrl(){const p=new URLSearchParams(location.search);state.view=p.get('view')==='ended'?'ended':'active';const within=Number(p.get('within'));state.within=state.view==='active'&&[3,7,14,30].includes(within)?within:null;state.vehicleClass=Object.hasOwn(classLabels,p.get('vehicleClass'))?p.get('vehicleClass'):'';state.cc=[...new Set(p.getAll('cc').filter(v=>Object.hasOwn(ccLabels,v)))];$('#within').value=state.within||'';$('#vehicleClass').value=state.vehicleClass;$$('input[name=cc]').forEach(i=>i.checked=state.cc.includes(i.value))}
$$('.tabs button').forEach(button=>button.addEventListener('click',()=>{if(button.dataset.view==='within30'){state.view='active';state.within=30;$('#within').value='30'}else{state.view=button.dataset.view;state.within=null;$('#within').value=''}render()}));
$('#filters').addEventListener('submit',event=>{event.preventDefault();state.within=state.view==='ended'?null:Number($('#within').value)||null;state.vehicleClass=$('#vehicleClass').value;state.cc=$$('input[name=cc]:checked').map(i=>i.value);render()});
$('#clearFilters').addEventListener('click',()=>{state.within=null;state.vehicleClass='';state.cc=[];$('#within').value='';$('#vehicleClass').value='';$$('input[name=cc]').forEach(i=>i.checked=false);render()});
readUrl();render();
